modLoader="neoforge"
loaderVersion="[1.0,)"
license="MIT"

[[mods]]
modId="scalablemobs"
version="1.0.0"
displayName="Scalable Mobs"
description='Mod que asigna niveles visibles a todos los mobs'

# Activar mixins
mixins = ["scalablemobs.mixins.json"]

[[dependencies.scalablemobs]]
modId="apothic_attributes"
mandatory=true
versionRange="[VERSION,)"
ordering="NONE"
side="BOTH"

