modLoader="neoforge"
loaderVersion="[1.0,)"
license="MIT"

[[mods]]
modId="scalablemobs"
version="0.2.0"
displayName="ScalableMobs"
description='A mod to make monsters levelup the deeper you go mining'

# Activar mixins
mixins = ["scalablemobs.mixins.json"]

